### PR TITLE
It give error on my xcode.

### PR DESCRIPTION
**Pull request by govi2010**

### CODE REVIEW

**Comment by kriefsacha** [comment]
I really need this too @shiv19 ! Is there any way you add this ? For swift 5

**Comment by shiv19** [comment]
@govi2010 @kriefsacha  This PR was supposed to be made to the "nativescript" branch, so I have reverted this PR, and made the changes you made here manually on the NativeScript branch.
Let me know if that works for you.

**Comment by shiv19** [comment]
@kriefsacha 
Had to replace it with
kCAFillRuleEvenOdd ? kCAFillRuleEvenOdd : CAShapeLayerFillRule.evenOdd

because CAShapeLayerFillRule.evenOdd is giving build error in the CI of my project.
image

**Comment by shiv19** [comment]
@kriefsacha 
Turns out that CAShapeLayerFillRule.evenOdd is a feature of swift 4.2+,
this pod was written with Swift 3.0, so I had to revert the change again,
are you changing the swift version for this plugin anywhere in your project?

**Comment by kriefsacha** [comment]
Hi, i use nativescript app tour, which use your plugin, and my project is written with swift 5. So i reallyyyy need it please don't remove it

**Comment by kriefsacha** [comment]
You can maybe at least for now putting that in another branch for those who need @shiv19

**Pull request merged**
